// <auto-generated />
namespace CustomerManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Begundatabasenormalisation2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Begundatabasenormalisation2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806180859054_Begun database normalisation 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
