// <auto-generated />
namespace CustomerManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedcompletedflagforinvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedcompletedflagforinvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210646012_Added completed flag for invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
